const ENABLE_HUE = false;
const COLOR_REFRESH_RATE = 200;
const POSITION_REFRESH_RATE = 50;
const POSITION_SPEED = 0.06;
const COLOR_MIX_COEFFICIENT = 0.1;

module.exports = {
    ENABLE_HUE,
    COLOR_REFRESH_RATE,
    POSITION_REFRESH_RATE,
    POSITION_SPEED,
    COLOR_MIX_COEFFICIENT,
};
