const ENABLE_HUE = false;
const ENABLE_HUE_ALTERNATING = false;
const COLOR_REFRESH_RATE = 200;
const POSITION_REFRESH_RATE = 50;
const POSITION_SPEED = 0.1;
const COLOR_MIX_COEFFICIENT = 0.1;

const BRICK_SCALE = 16;

const BPM_CONST = 123;
const TRIANGLE_GENERATING_RATE = 60 * 1000 / BPM_CONST;

module.exports = {
    BRICK_SCALE,
    ENABLE_HUE,
    ENABLE_HUE_ALTERNATING,
    COLOR_REFRESH_RATE,
    POSITION_REFRESH_RATE,
    POSITION_SPEED,
    COLOR_MIX_COEFFICIENT,
    TRIANGLE_GENERATING_RATE,
};
