const LETTER_SPACING = 64;
const JUMP_UNIT_HEIGHT = -16;
const ANAGRAM_SET_CYCLE_TIME = 40000;
const ANAGRAM_CYCLE_TIME = 5500;
const LETTER_TRANSITION_TIME = 1000;
const WORD_TRANSITION_TIME = 600;
const LETTER_TILT_TIME = 600;

module.exports = {
    LETTER_SPACING,
    JUMP_UNIT_HEIGHT,
    ANAGRAM_SET_CYCLE_TIME,
    ANAGRAM_CYCLE_TIME,
    LETTER_TRANSITION_TIME,
    WORD_TRANSITION_TIME,
    LETTER_TILT_TIME,
};
